# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '预定信息', 'verbose_name_plural': '预定信息'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '会议室信息', 'verbose_name_plural': '会议室信息'},
        ),
        migrations.AlterField(
            model_name='room',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='会议室名称'),
        ),
        migrations.AlterField(
            model_name='room',
            name='num',
            field=models.IntegerField(verbose_name='容纳人数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(max_length=32, verbose_name='电话'),
        ),
    ]
